/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns.h"
#include "shared.h"
using namespace std;

map<string,string> dns1;

char **
resolver_nombre_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;
	
	result = "No se ha encontrado la ip asociada al host.";
	
	map<string,string>::iterator it = dns1.find(arg1);
	
	if (it != dns1.end())
		result = (char*)(it->second).c_str();

	return &result;
}

int *
registrar_equipo_1_svc(char *arg1, char *arg2,  struct svc_req *rqstp)
{
	static int result;
	char *host_completo = strcat(arg1,".red1");
	dns1.insert(pair<string,string>(arg1,arg2));
	result = 1;

	cout << "Lista de equipos DNS1:\n\n";
	for (auto& x: dns1) {
    	cout << x.first << " : " << x.second << '\n';
  	}
  	cout << "\n";

	return &result;
}

int *
borrar_equipo_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int result;

	result = dns1.erase(arg1);

	cout << "Lista de equipos DNS1:\n\n";
	for (auto& x: dns1) {
    	cout << x.first << " : " << x.second << '\n';
  	}

  	cout << "\n";
	return &result;
}

