/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns2.h"
using namespace std;
char * *resultado_resolver_nombre_1;
	char *resolver_nombre_1_arg1;
	int  *resultado_registrar_equipo_1;
	char *registrar_equipo_1_arg1;
	char *registrar_equipo_1_arg2;
	int  *resultado_borrar_equipo_1;
	char *borrar_equipo_1_arg1;
	char * *result_4;
	char *enviar_peticion_1_arg1;
	char *operacion;

void
dns2_1(char *host)
{
	CLIENT *clnt;
	

#ifndef	DEBUG
	clnt = clnt_create (host, DNS2, DNS2VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if (strcmp(operacion,"resolver") == 0){
		resultado_resolver_nombre_1 = resolver_nombre_1(resolver_nombre_1_arg1, clnt);
		if (resultado_resolver_nombre_1 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
	} else if (strcmp(operacion,"registrar") == 0) {

		resultado_registrar_equipo_1 = registrar_equipo_1(registrar_equipo_1_arg1, registrar_equipo_1_arg2, clnt);
		if (resultado_registrar_equipo_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	} else if (strcmp(operacion,"borrar") == 0) {

		resultado_borrar_equipo_1 = borrar_equipo_1(borrar_equipo_1_arg1, clnt);
		if (resultado_borrar_equipo_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}	
	}

	

	/*
	result_4 = enviar_peticion_2(enviar_peticion_2_arg1, clnt);
	if (result_4 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;


	if (argc < 4) {
		cout << "USO: " << argv[0] << " server_host operación nombre ip\n\n" <<
			"Donde \"operación\" = registrar | borrar | resolver\n" <<
			"Para REGISTRAR: rellenar los parámetros NOMBRE (SIN subred) e IP. La subred se añade " <<
			"de forma automática en el DNS apropiado en función de la IP\n" <<
			"Para BORRAR: basta con incluir el parámetro NOMBRE (CON subred)\n" <<
			"Para RESOLVER: basta con incluir el parámetro NOMBRE (CON subred)\n\n";
		exit (1);
	}

	host = argv[1];
	operacion = argv[2];
	borrar_equipo_1_arg1 = argv[3];
	registrar_equipo_1_arg1 = argv[3];
	resolver_nombre_1_arg1 = argv[3];
	registrar_equipo_1_arg2 = argv[4];
	
	dns2_1 (host);

	if(strcmp(operacion,"registrar") == 0){
		if (*resultado_registrar_equipo_1 == -1){
			cout << "No has introducido una IP correcta.";
		} else if (*resultado_registrar_equipo_1 == 0){
			cout << "No se ha registrado el equipo (no hay un DNS cubriendo esta subred).";
		} else if (*resultado_registrar_equipo_1 == 1) {
			cout << "Equipo registrado en DNS1";
		} else if (*resultado_registrar_equipo_1 == 2) {
			cout << "Equipo registrado en DNS2";
		}
	}
	else if (strcmp(operacion,"borrar") == 0)
		cout << "Numero de equipos borrados: " << *resultado_borrar_equipo_1;
	else if (strcmp(operacion,"resolver") == 0)
		cout << *resultado_resolver_nombre_1;

	cout << "\n";
	exit (0);
}
