/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNS2_H_RPCGEN
#define _DNS2_H_RPCGEN

#include <rpc/rpc.h>
#include <cstdio>
#include <map>
#include <string>
#include <iostream>


#ifdef __cplusplus
extern "C" {
#endif


struct registrar_equipo_1_argument {
	char *arg1;
	char *arg2;
};
typedef struct registrar_equipo_1_argument registrar_equipo_1_argument;

#define DNS2 0x20000001
#define DNS2VERS 1
#define DNS 0x20000002
#define DNSVERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define RESOLVER_NOMBRE1 1
extern  char ** resolver_nombre1_1(char *, CLIENT *);
#define REGISTRAR_EQUIPO1 2
extern  int * registrar_equipo1_1(char *, char *, CLIENT *);
#define BORRAR_EQUIPO1 3
extern  int * borrar_equipo1_1(char *, CLIENT *);
extern int dns_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
#define RESOLVER_NOMBRE 5
extern  char ** resolver_nombre_1_svc(char *, struct svc_req *);
#define REGISTRAR_EQUIPO 6
extern  int * registrar_equipo_1_svc(char *, char *, struct svc_req *);
#define BORRAR_EQUIPO 7
extern  int * borrar_equipo_1_svc(char *, struct svc_req *);
extern int dns2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern char * obtener_octeto3(char *);

#else /* K&R C */
#define RESOLVER_NOMBRE1 1
extern  char ** resolver_nombre1_1();
#define REGISTRAR_EQUIPO1 2
extern  int * registrar_equipo1_1();
#define BORRAR_EQUIPO1 3
extern  int * borrar_equipo1_1();
extern int dns_1_freeresult ();
#define RESOLVER_NOMBRE 5
extern  char ** resolver_nombre_1_svc();
#define REGISTRAR_EQUIPO 6
extern  int * registrar_equipo_1_svc();
#define BORRAR_EQUIPO 7
extern  int * borrar_equipo_1_svc();
extern int dns2_1_freeresult ();
extern char * obtener_octeto3(char *);
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registrar_equipo_1_argument (XDR *, registrar_equipo_1_argument*);

#else /* K&R C */
extern bool_t xdr_registrar_equipo_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNS2_H_RPCGEN */
