/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dns2.h"
#include "shared.h"
#include <arpa/inet.h>
using namespace std;

map<string,string> dns2;

CLIENT *clnt;
char* host= "localhost";

char * obtener_octeto3(char *arg1){
	char * host = (char*) malloc(strlen(arg1) + 1);
	strcpy(host, arg1);
	char * octeto1,*octeto2,*octeto3;
	octeto1 = strtok(host,".");
	octeto2 = strtok(NULL,".");
	octeto3 = strtok(NULL,".");
	return octeto3;
}

char **
resolver_nombre_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;
	
	clnt = clnt_create (host, DNS, DNSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	result = "No se ha encontrado la ip asociada al host.";
	
	map<string,string>::iterator it = dns2.find(arg1);
	
	if (it != dns2.end())
		result = (char*)(it->second).c_str();
	else
		result = *resolver_nombre1_1(arg1,clnt);

	clnt_destroy (clnt);
	return &result;
}

int *
registrar_equipo_1_svc(char *arg1, char *arg2,  struct svc_req *rqstp)
{
	static int result;

	clnt = clnt_create (host, DNS, DNSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result = -1;

	struct sockaddr_in sa;
    int ip_valida = inet_pton(AF_INET, arg2, &(sa.sin_addr));

	if ( ip_valida != 0 ){
		result =0;
		char *octeto3 = obtener_octeto3(arg2);
		char *host_completo;
		if(strcmp(octeto3,"2") == 0){
			host_completo = strcat(arg1,".red2");
			dns2.insert(pair<string,string>(host_completo,arg2));
			result=2;
		} else if(strcmp(octeto3,"1") == 0)
			result = *registrar_equipo1_1(arg1, arg2, clnt);
	}
	
	cout << "Lista de equipos DNS2:\n\n";
	for (auto& x: dns2) {
    	cout << x.first << " : " << x.second << '\n';
  	}
  	cout << "\n";
  	clnt_destroy (clnt);
	return &result;
}

int *
borrar_equipo_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int result;

	clnt = clnt_create (host, DNS, DNSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


	result = dns2.erase(arg1);
		
	if (result == 0)
		result = *borrar_equipo1_1(arg1, clnt);

	cout << "Lista de equipos DNS2:\n\n";
	for (auto& x: dns2) {
    	cout << x.first << " : " << x.second << '\n';
  	}
  	cout << "\n";
  	clnt_destroy (clnt);

	return &result;
}